import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const styles = {
  display: "flex",
  justifyContent: "center",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={styles}>
        {children}
      </body>
    </html>
  );
}
